dist: bionic
sudo: required

language: python
python:
  - "3.7"
# command to install system packages
before_install:
  - sudo apt-get install -y libssl-dev
# command to install dependencies
install:
  - pip install mindspore
# command to run tests
script: python -c "import mindspore;print(mindspore.__version__)"

services:
  - docker
